
language: python
python:   "3.6"
os:       linux
dist:     xenial

git:
  depth: 1

# safelist
branches:
  only:
  - devel

env:
  global:
    - CODECOV_TOKEN="c7e0d993-d31a-4d39-8ffa-07c30ea73e48"
    - COVERAGE=false
    - LOC=/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages
    - PYTEST="coverage run --include=$LOC/radical/pilot/* -m pytest -ra --timeout=600 -vvv --showlocals"
    
  jobs:
    - MAIN_CMD="$PYTEST tests/" COVERAGE=true
    - MAIN_CMD="ru-runcheck.sh flake8 diff"
    - MAIN_CMD="ru-runcheck.sh pylint diff"
    - MAIN_CMD="ru-runcheck.sh flake8 tests/ bin/"
    - MAIN_CMD="ru-runcheck.sh pylint tests/ bin/"
      #    - MAIN_CMD="ru-runcheck.sh flake8 tests/ bin/ examples/"
      #    - MAIN_CMD="ru-runcheck.sh pylint tests/ bin/ examples/"

before_install:
  - uname -a
  - ulimit -a
  - python -V

# command to install dependencies
install:
  - pip install .
  - pip install coverage
  - pip install flake8
  - pip install flake8-per-file-ignores
  - pip install pycodestyle
  - pip install pylint
  - pip install codecov
  - pip install pytest
  - pip install pytest-timeout
  
before_script:
  - tmpLOC=`which python`
  - tmpLOC=(${tmpLOC///bin/ })
  - LOC=`find $tmpLOC/lib -name "site-packages"`
  - echo $tmpLOC
  - echo $LOC

script:
  - echo $MAIN_CMD
  - eval $MAIN_CMD

after_success:
  - |
    if [[ $COVERAGE == 'true' ]]; then \
      coverage combine; \
      coverage xml; \
      coverage report; \
      curl -s https://codecov.io/bash | bash
    fi

notifications:
  email:
    recipients: andre@merzky.net
    on_success: change
    on_failure: always

